export const GET_INVENTARIO_REQUEST = "GET_INVENTARIO_REQUEST";
export const GET_INVENTARIO_SUCCESS = "GET_INVENTARIO_SUCCESS";
export const GET_INVENTARIO_FAIL = "GET_INVENTARIO_FAIL";

export const GET_INVENTARIO_DETAILS_REQUEST = "GET_INVENTARIO_DETAILS_REQUEST";
export const GET_INVENTARIO_DETAILS_SUCCESS = "GET_INVENTARIO_DETAILS_SUCCESS";
export const GET_INVENTARIO_DETAILS_FAIL = "GET_INVENTARIO_DETAILS_FAIL";
export const GET_INVENTARIO_DETAILS_RESET = "GET_INVENTARIO_DETAILS_RESET";